- name: install apache server
  hosts: all
  become: yes
  tasks:
    - name: Install apache httpd
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
      notify:
        - enable and restart apache2
    - name: copy file to dest
      ansible.builtin.copy:
        src: context.txt
        dest: /var/www/html/info.php
        remote_src: yes
    - name: install php modules
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
  handlers:
    - name: enable and restart apache2
      ansible.builtin.systemd:
        name: apache2
        enabled: yes
        state: restarted
